import numpy as np

MIN_SLOPE_RESISTANCE_VALUE = 0.01
MAX_SLOPE_RESISTANCE_VALUE = 100.0
MIN_ROAD_GRAVITY_VALUE = 0.01
MAX_ROAD_GRAVITY_VALUE = 100.0
MIN_SPREAD_VALUE = 0.01
MAX_SPREAD_VALUE = 100.0
MIN_DIFFUSION_VALUE = 0.01
MAX_DIFFUSION_VALUE = 100.0
MIN_BREED_VALUE = 0.01
MAX_BREED_VALUE = 100.0
MAX_ROAD_VALUE = 100

DIGITS_IN_YEAR = 4
LOW = 0
MED = 1
HIGH = 2

CALL_STACK_SIZE = 100
MAX_PROBABILITY_COLORS = 100
PI = np.pi

REGION_SIZE = 30
DELTA_PHASE2_SENSITIVITY = 1.0
SELF_MOD_SENSITIVITY = 20.0
MIN_YEARS_BETWEEN_TRANSITIONS = 5
MIN_NGHBR_TO_SPREAD = 2
MAX_URBAN_YEARS = 15
MAX_ROAD_YEARS = 15
MAX_LANDUSE_YEARS = 2

RESTART_FILE = "restart_file.data"

PACKED = 1
UNPACKED = 0
NOTPACKED = 0
PHASE0G = 3
PHASE1G = 4
PHASE2G = 5
PHASE3G = 6
PHASE4G = 7
PHASE5G = 8
LT = 0
LE = 1
EQ = 2
NE = 3
GE = 4
GT = 5

globals_h_sccs_id = "@(#)globals.h	1.259	12/4/00"

glb_i = 0
glb_mype = 0
glb_npes = 0
msg_buf = 'message here'
glb_filename = 'filename here'
glb_token = 0
